version: '3.8'
volumes:
  mongo_vol:

networks:
  produto_net:
    driver: bridge

services:
  api:
    image: rodrigoturatti/api-produto:${TAG}
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    networks:
      - produto_net
    environment:
      - MONGODB_URI=mongodb://mongouser:mongopwd@mongodb:27017/produto

  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db
    networks:
      - produto_net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
      - MONGO_INITDB_DATABASE=produto